name: 'Build desktop vZome'
description: 'Use Gradle to build the desktop version of vZome'
# inputs:
  # who-to-greet:  # id of input
  #   description: 'Who to greet'
  #   required: true
  #   default: 'World'
# outputs:
  # random-number:
  #   description: "Random number"
  #   value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"

  steps:
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Build with Gradle
      shell: bash
      run: |
        date
        chmod +x gradlew
        ./gradlew clean jpackage
        ls desktop/build/jpackage



    # - name: Set Greeting
    #   run: echo "Hello $INPUT_WHO_TO_GREET."
    #   shell: bash
    #   env:
    #     INPUT_WHO_TO_GREET: ${{ inputs.who-to-greet }}

    # - name: Random Number Generator
    #   id: random-number-generator
    #   run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
    #   shell: bash

    # - name: Set GitHub Path
    #   run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
    #   shell: bash
    #   env:
    #     GITHUB_ACTION_PATH: ${{ github.action_path }}

