# This is a basic workflow that is manually triggered

name: vZome desktop build

on:
  workflow_dispatch:

env:
  BUILD_NUMBER: ${{ github.run_number }}
  GIT_COMMIT: ${{ github.sha }}
  # TODO connect these to secrets
  # NOTE: They have nothing to do with running this GitHub Action;
  #   they are for vZome to make runtime API calls to GitHub.
  GITHUB_CLIENT_SECRET: ${{ secrets.VZOME_GITHUB_CLIENT_SECRET }}
  GITHUB_CLIENT_ID: ${{ secrets.VZOME_GITHUB_CLIENT_ID }}


jobs:
  build-macos:
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: 'true'
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Control Timezone
      uses: szenius/set-timezone@v1.0
      with:
        timezoneMacos: "America/Los_Angeles"
    - name: Get current date
      run: date
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      env: 
        MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
        MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
        SIGNING_KEYCHAIN: build.keychain
      run: |
        echo $MACOS_CERTIFICATE | base64 -D > certificate.p12
        security create-keychain -p KeychainPwd $SIGNING_KEYCHAIN
        security default-keychain -s $SIGNING_KEYCHAIN
        security unlock-keychain -p KeychainPwd $SIGNING_KEYCHAIN
        security import certificate.p12 -k $SIGNING_KEYCHAIN -P $MACOS_CERTIFICATE_PWD -T /usr/bin/codesign
        security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k KeychainPwd $SIGNING_KEYCHAIN
        ./gradlew --info clean jpackage 
    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/dreamhost.key
        chmod 600 ~/.ssh/dreamhost.key
        cat >>~/.ssh/config <<END
        Host dreamhost
          HostName sandy.dreamhost.com
          User scottvorthmann
          IdentityFile ~/.ssh/dreamhost.key
          StrictHostKeyChecking no
        END
      env:
        SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Publish MacOS build to DreamHost
      run: |
        platform=mac sftp -b - dreamhost <<END
          cd vzome.com/quarantine
          mput desktop/build/jpackage/vZome-*.dmg	
        END

  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: |
        ./gradlew clean jpackage
        ls desktop/build/jpackage
    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/dreamhost.key
        chmod 600 ~/.ssh/dreamhost.key
        cat >>~/.ssh/config <<END
        Host dreamhost
          HostName sandy.dreamhost.com
          User scottvorthmann
          IdentityFile ~/.ssh/dreamhost.key
          StrictHostKeyChecking no
        END
      env:
        SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Publish Linux build to DreamHost
      run: |
        platform=linux sftp -b - dreamhost <<END
          cd vzome.com/quarantine/linux
          mput desktop/build/jpackage/vzome_*.deb
        END

  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: |
        ./gradlew clean jpackage
        ls desktop/build/jpackage
    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/dreamhost.key
        chmod 600 ~/.ssh/dreamhost.key
        echo 'Host dreamhost' > ~/.ssh/config
        echo '  HostName sandy.dreamhost.com' >> ~/.ssh/config
        echo '  User scottvorthmann' >> ~/.ssh/config
        echo '  IdentityFile ~/.ssh/dreamhost.key' >> ~/.ssh/config
        echo '  StrictHostKeyChecking no' >> ~/.ssh/config
      env:
        SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Publish Windows build to DreamHost
      run: |
        echo "cd vzome.com/quarantine/windows" > batchfile.txt
        echo "mput desktop/build/jpackage/vZome-*.exe" >> batchfile.txt
        platform=windows sftp -b batchfile.txt dreamhost

