# This is a basic workflow that is manually triggered

name: MacOS desktop build

on:
  workflow_dispatch:

env:
  BUILD_NUMBER: ${{ github.run_number }}
  GIT_COMMIT: ${{ github.sha }}
  # TODO connect these to secrets
  # NOTE: They have nothing to do with running this GitHub Action;
  #   they are for vZome to make runtime API calls to GitHub.
  GITHUB_CLIENT_SECRET: ''
  GITHUB_CLIENT_ID: ''


jobs:
  build-macos:
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew clean createAppZip
    - name: Archive MacOS build
      uses: actions/upload-artifact@v2
      with:
        name: vZome-MacOSX-7.1.${{ github.run_number }}
        path: desktop/platform/mac/build/macApp/vZome-*.app

  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew clean distZip
    - name: Archive Linux build
      uses: actions/upload-artifact@v2
      with:
        name: vZome-Linux-7.1.${{ github.run_number }}
        path: desktop/build/distributions/vZome-Linux-*.zip
