
name: Build Jekyll site and deploy to Dreamhost

on:
  workflow_dispatch:

jobs:
  jekyll-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          build_only: true
      - name: List files
        run: ls .
