# This is a basic workflow to help you get started with Actions

name: JSweet legacy bundle

# Controls when the workflow will run
on:
  push:
    branches: [ master ]
    paths:
      - 'core/src/jsweet/**'
      - 'core/src/main/java/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Grant execute permissions
        run: chmod +x gradlew cicd/jsweet-legacy-code.bash

      - name: Build with Gradle and JSweet
        run: cicd/jsweet-legacy-code.bash

      - name: Archive Generated JS
        uses: actions/upload-artifact@v2
        with:
          name: transpiled-java
          path: online/src/wc/legacy/transpiled-java.js

      # TODO: publish to npm.pkg.github.com; see https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages
      
