# This is a basic workflow to help you get started with Actions

name: JSweet legacy bundle

# Controls when the workflow will run
on:
  push:
    branches: [ master ]
    paths:
      - 'core/src/jsweet/**'
      - 'core/src/main/java/**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout vZome source
        uses: actions/checkout@v2

      - name: Checkout modified jsweet-gradle-plugin
        uses: actions/checkout@v2
        with:
          repository: vorth/jsweet-gradle-plugin
          ref: issue-35-javaCompilerExtraOptions
          path: plugin

      - name: Build & deploy jsweet-gradle-plugin
        run: |
          pwd
          cd plugin
          pwd
          chmod +x gradlew
          ./gradlew publishToMavenLocal -DskipSigning=true
          cd ..

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Gradle and JSweet
        run: |
          pwd
          chmod +x gradlew cicd/jsweet-legacy-code.bash
          cicd/jsweet-legacy-code.bash

      - name: Archive Generated JS
        uses: actions/upload-artifact@v2
        with:
          name: transpiled-java
          path: online/src/wc/legacy/transpiled-java.js

      # TODO: publish to npm.pkg.github.com; see https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages
      
