# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: vZome Online build

on:
  workflow_dispatch:

env:
  BUILD_NUMBER: ${{ github.run_number }}
  GIT_COMMIT: ${{ github.sha }}

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.3.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2

    - name: Checkout modified jsweet-gradle-plugin
      uses: actions/checkout@v2
      with:
        repository: vorth/jsweet-gradle-plugin
        ref: issue-35-javaCompilerExtraOptions
        path: plugin

    - name: Build & deploy jsweet-gradle-plugin
      run: |
        pwd
        cd plugin
        pwd
        chmod +x gradlew
        ./gradlew publishToMavenLocal -DskipSigning=true
        cd ..

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Grant execute permissions
      run: chmod +x gradlew cicd/build-online.bash
    - name: Build with Gradle and Yarn
      run: cicd/build-online.bash
    - name: Archive vZome Online build
      uses: actions/upload-artifact@v2
      with:
        name: online-app
        path: online/dist/online.tgz

