# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: vZome Online build

on:
  workflow_dispatch:

env:
  BUILD_NUMBER: ${{ github.run_number }}
  GIT_COMMIT: ${{ github.sha }}

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: 'true'

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build with Gradle and Yarn
      run: |
        chmod +x gradlew cicd/online.bash
        cicd/online.bash prod

    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/dreamhost.key
        chmod 600 ~/.ssh/dreamhost.key
        cat >>~/.ssh/config <<END
        Host dreamhost
          HostName $HOSTING_FQDN
          User scottvorthmann
          IdentityFile ~/.ssh/dreamhost.key
          StrictHostKeyChecking no
        END
        cat ~/.ssh/config
      env:
        SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        HOSTING_FQDN: ${{ secrets.HOSTING_FQDN }}

    - name: Publish Online build to DreamHost
      run: |
        sftp -b - dreamhost <<END
          cd vzome.com/
          put online/dist/online.tgz	
        END
        ssh dreamhost ./install-vzome-online.bash


