# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: core unit & regression tests

on:
  push:
    branches: [ master ]
    paths:
      - 'core/src/main/java/**'
      - 'core/src/regression/**'
      - 'core/src/test/java/**'
      - 'core/build.gradle'
  pull_request:
    branches: [ master ]
    paths:
      - 'core/src/main/java/**'
      - 'core/src/regression/**'
      - 'core/src/test/java/**'
      - 'core/build.gradle'
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew test regression
